- name: get restarts out of the way to ensure master is available for clustering
  meta: flush_handlers

- name: enable EPEL repos
  yum: name=epel-release

- name: install python pip
  yum: name=python-pip

- name: install influxdb python library
  pip: name=influxdb

- name: wait for influxdb to be started
  wait_for: host={{ private_ip }} port=8086 timeout=60

- name: create influxdb admin user
  influxdb_user:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    user: "{{ influxdb_admin_user }}"
    password: "{{ influxdb_admin_password }}"
    privilege: ALL

- name: create influxdb telegraf user
  influxdb_user:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    user: "{{ influxdb_telegraf_user }}"
    password: "{{ influxdb_telegraf_password }}"
    database: telegraf
    privilege: ALL

- name: create retention policies
  influxdb_retention_policy:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    database: telegraf
    duration: "{{ item.duration }}"
    replication: "{{ item.replication }}"
    is_default_policy: "{{ item.default | default(false) }}"
  with_items: "{{ influxdb_retention_policies }}"

- name: create downsamplings for influxdb measurements
  influxdb_downsample:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    database: telegraf
    retentions: 5m:rp_60d,30m:rp_52w
    measurements: "{{ influxdb_measurement_fields_to_downsample_on_mean }}"
    prune: true
