- name: install influxdb telegraf on RedHat
  yum: name=telegraf state=latest
  when: ansible_os_family == 'RedHat'

- name: install influxdb telegraf on Debian
  apt: name=telegraf state=latest
  when: ansible_os_family == 'Debian'

- name: install telegraf setup
  template: src=telegraf.conf dest=/etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: start and enable telegraf
  service: name=telegraf state=started enabled=yes
